FROM mcr.microsoft.com/playwright:v1.37.1-jammy

ENV APP_PATH /usr/src/app

# Set Application Environment
WORKDIR ${APP_PATH}

# Copy + Install playwright project
COPY ./test-module ./
RUN npm install

CMD npm run test
